PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>

SELECT ?hub COUNT(DISTINCT ?instance)
WHERE {
  GRAPH <http://localhost:8890/test3> { 
    ?hub rdf:type <http://id.loc.gov/ontologies/bibframe/Hub> .
    ?hub bf:hasExpression ?work .
    ?work bf:hasInstance ?instance .
  }
}