PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>

SELECT DISTINCT ?hub ?hubLabel ?work ?workLabel
WHERE {
  GRAPH <http://localhost:8890/test2> { 
    ?hub rdf:type <http://id.loc.gov/ontologies/bibframe/Hub> .
    ?hub bf:hasExpression ?work, ?work2 .
    FILTER(?work != ?work2) .
    ?work bf:title/bf:mainTitle ?workLabel .
    ?hub bf:title/bf:mainTitle ?hubLabel .
  }
}